name: Pull request validation

on:
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"
          bundler-cache: true
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle config with "development test"
          bundle install --jobs 4 --retry 3
      - name: standardsrb
        run: |
          bundle exec rake standard
