name: Pull request validation

on:
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - name: standardsrb
        run: |
          bundle exec rake standard
